### ISSUE TITLE
Commit Messages  Need Variety

### ISSUE THREAD

**Issue by lambdaknight** [LindseyB/dummy#1]
Maybe `fortune` could help? Maybe generate a haiku from some ML algorithm?

**Comment by LindseyB** [comment]
I've added some variety now so I'm gonna close this but I'm also gonna use this comment to upload the floating dumpster. 
![FirmUnawareDungbeetle-size_restricted](https://user-images.githubusercontent.com/33750/84051448-2ed5ef80-a97d-11ea-9ad7-dd5366cf2ca9.gif)
